#!/usr/bin/env bash

# An installer script (for Dockerfiles).
# Reference: https://github.com/casey/just/blob/master/bin/package

set -euxo pipefail

# VERSION="${VERSION:-latest}"
VERB_URL="https://github.com/chaseruskin/verb"

PYTHON_INSTALLER="${PYTHON_INSTALLER:-pip}"
HDL_INSTALLER="${HDL_INSTALLER:-orbit}"
RUST_INSTALLER="${RUST_INSTALLER:-cargo}"

echo "Installing verb ..."

echo "Installing verb software library (Python) ..."
$PYTHON_INSTALLER install "git+$VERB_URL.git@trunk#egg=verb&subdirectory=src/lib/python"

echo "Installing verb hardware library (VHDL/Verilog/SystemVerilog) ..."
$HDL_INSTALLER install verb --url $VERB_URL/archive/refs/heads/trunk.zip

echo "Installing verb binary (Rust) ..."
$RUST_INSTALLER install --bin verb --git $VERB_URL
