// This interface is automatically @generated by Verb.
// It is not intended for manual editing.
interface ram_if #(
    parameter int ADDR_WIDTH,
    parameter int DATA_WIDTH
);
    logic[ADDR_WIDTH-1:0] waddr;
    logic[ADDR_WIDTH-1:0] raddr;
    logic                 wen;
    logic[DATA_WIDTH-1:0] wdata;
    logic[DATA_WIDTH-1:0] rdata;
endinterface

module ram_tb 
    import verb::*;
#(
  parameter int ADDR_WIDTH = 4,
  parameter int DATA_WIDTH = 8
);

    logic clk = 1'b0;
    logic rst = 1'b0;

    localparam int TIMEOUT_LIMIT = 1_000;

    ram_if #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH)
    ) bfm();

    ram_if #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH)
    ) mdl();


    // instantiate the device under test
    ram #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH)
    ) uX (
        .clk(clk),
        .rst(rst),
        .waddr(bfm.waddr),
        .raddr(bfm.raddr),
        .wen(bfm.wen),
        .wdata(bfm.wdata),
        .rdata(bfm.rdata)
    );
    
    // produce a clock with 50% duty cycle
    always #(20ns) clk = ~clk;

    // drive incoming transactions
    always begin: driver 
        static int inputs = $fopen("inputs.txt", "r");

        // perform initial reset
        sync_hi_async_lo(clk, rst, 2);

        while(!$feof(inputs)) begin
            send(inputs);
            @(negedge clk);
        end
        wait(0);
    end

    // check outgoing transactions for correctness
    always begin: monitor
        static int outputs = $fopen("outputs.txt", "r");
        
        observe(clk, rst, 1'b1, 100, "rst enabled");
        observe(clk, rst, 1'b0, 100, "rst disabled");

        while(!$feof(outputs)) begin
            recv(outputs);
            @(posedge clk);
        end
        finish();
    end

    // This task is automatically @generated by Verb.
    // It is not intended for manual editing.
    task send(int fd);
        automatic string line;
        // Read next set of input values from file
        if(!$feof(fd)) begin
            $fgets(line, fd);
            $sscanf(parse(line), "%b", bfm.waddr);
            $sscanf(parse(line), "%b", bfm.raddr);
            $sscanf(parse(line), "%b", bfm.wen);
            $sscanf(parse(line), "%b", bfm.wdata);
        end
    endtask


    // This task is automatically @generated by Verb.
    // It is not intended for manual editing.
    task recv(int fd);
        automatic string line;
        // Read expected output values from file
        if(!$feof(fd)) begin
            $fgets(line, fd);
            $sscanf(parse(line), "%b", mdl.rdata);
        end
        // Compare received ouputs with expected outputs
        assert_eq(bfm.rdata, mdl.rdata, "rdata");
    endtask

endmodule
